name: secure_password_manager
description: A world-class, production-ready password manager built with Flutter featuring end-to-end encryption, intuitive UI, and comprehensive password management tools.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  path: ^1.9.0
  pointycastle: ^3.9.1
  encrypt: ^5.0.3
  crypto: ^3.0.3
  convert: ^3.1.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  msix: ^3.16.7

msix_config:
  display_name: Cipher Nest
  publisher_display_name: Password Manager
  identity_name: com.local.securepasswordmanager
  msix_version: 1.0.0.1
  logo_path: windows\runner\resources\app_icon.ico
  capabilities: internetClient

flutter:
  uses-material-design: true
  assets:
    - assets/branding/
